# Data analysis in Python

In [3]:
#importing the libraries 
import numpy as np
import pandas as pd

In [4]:
data=pd.read_csv("sales.csv")

In [5]:
data

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [6]:
#importing data directly from system

In [7]:
data=pd.read_csv("C:\Users\ASUS\OneDrive\Desktop\index_1.csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1518765845.py, line 1)

In [8]:
#unicode error - file read - 2 slashes

In [9]:
data=pd.read_csv("C:\\Users\\ASUS\\OneDrive\\Desktop\\index_1.csv")

In [8]:
data

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [9]:
data.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [10]:
data.tail()

,date,datetime,cash_type,card,money,coffee_name
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   object
 1   datetime     3636 non-null   object
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

In [12]:
data.describe()

             money
count  3636.000000
mean     31.746859
std       4.919926
min      18.120000
25%      27.920000
50%      32.820000
75%      35.760000
max      40.000000

In [13]:
data.shape

(3636, 6)

In [14]:
data.columns

Index(['date', 'datetime', 'cash_type', 'card', 'money', 'coffee_name'], dtype='object')

In [15]:
# data cleaning
#is na tells the values null

In [16]:
data.isna().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

# Data cleaning

In [17]:
# missing values 
#duplicate remove
# standadrization of data
#outliers removal

In [18]:
data

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [19]:
# to see all the rows of thd data

In [22]:
#pd.set_option('display.max_rows',None)
#pd.set_option('display.max_columns',None)
#data

In [21]:
#daradata cleaning

In [23]:
data.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [24]:
data['cash_type'].value_counts()

cash_type
card    3547
cash      89
Name: count, dtype: int64

In [25]:
# we use value counts to check the frequency of the number of ocuurences of a value

In [26]:
data[data['cash_type']=='cash']['card'].isnull().sum()

np.int64(89)

In [32]:
# filling missing values
#fillna is used to fill the missing values

In [28]:
data['card']=data['card'].fillna('Cash_Transaction')

In [29]:
data

            date                 datetime cash_type                 card  \
0     2024-03-01  2024-03-01 10:15:50.520      card  ANON-0000-0000-0001
1     2024-03-01  2024-03-01 12:19:22.539      card  ANON-0000-0000-0002
2     2024-03-01  2024-03-01 12:20:18.089      card  ANON-0000-0000-0002
3     2024-03-01  2024-03-01 13:46:33.006      card  ANON-0000-0000-0003
4     2024-03-01  2024-03-01 13:48:14.626      card  ANON-0000-0000-0004
5     2024-03-01  2024-03-01 15:39:47.726      card  ANON-0000-0000-0005
6     2024-03-01  2024-03-01 16:19:02.756      card  ANON-0000-0000-0006
7     2024-03-01  2024-03-01 18:39:03.580      card  ANON-0000-0000-0007
8     2024-03-01  2024-03-01 19:22:01.762      card  ANON-0000-0000-0008
9     2024-03-01  2024-03-01 19:23:15.887      card  ANON-0000-0000-0008
10    2024-03-01  2024-03-01 19:29:17.391      card  ANON-0000-0000-0009
11    2024-03-02  2024-03-02 10:22:06.957      card  ANON-0000-0000-0010
12    2024-03-02  2024-03-02 10:30:35.668      cash     Cash_Transaction
13    2024-03-02  2024-03-02 10:41:41.249      card  ANON-0000-0000-0011
14    2024-03-02  2024-03-02 11:59:45.484      card  ANON-0000-0000-0012
15    2024-03-02  2024-03-02 14:38:35.535      card  ANON-0000-0000-0013
16    2024-03-02  2024-03-02 16:37:24.475      card  ANON-0000-0000-0014
17    2024-03-02  2024-03-02 17:34:54.969      card  ANON-0000-0000-0004
18    2024-03-03  2024-03-03 10:10:43.981      cash     Cash_Transaction
19    2024-03-03  2024-03-03 10:27:18.561      card  ANON-0000-0000-0015
20    2024-03-03  2024-03-03 11:33:56.118      card  ANON-0000-0000-0016
21    2024-03-03  2024-03-03 12:26:56.098      card  ANON-0000-0000-0012
22    2024-03-03  2024-03-03 13:09:36.321      card  ANON-0000-0000-0017
23    2024-03-03  2024-03-03 17:06:40.271      card  ANON-0000-0000-0018
24    2024-03-03  2024-03-03 17:08:45.895      card  ANON-0000-0000-0019
25    2024-03-03  2024-03-03 18:03:23.369      card  ANON-0000-0000-0020
26    2024-03-03  2024-03-03 18:04:27.946      card  ANON-0000-0000-0020
27    2024-03-03  2024-03-03 18:08:04.959      card  ANON-0000-0000-0020
28    2024-03-04  2024-03-04 10:03:51.994      card  ANON-0000-0000-0001
29    2024-03-04  2024-03-04 10:54:50.958      card  ANON-0000-0000-0021
30    2024-03-04  2024-03-04 11:05:16.184      card  ANON-0000-0000-0012
31    2024-03-04  2024-03-04 14:04:37.734      card  ANON-0000-0000-0022
32    2024-03-05  2024-03-05 09:59:52.651      card  ANON-0000-0000-0001
33    2024-03-05  2024-03-05 14:34:55.963      card  ANON-0000-0000-0023
34    2024-03-05  2024-03-05 17:34:06.043      card  ANON-0000-0000-0024
35    2024-03-05  2024-03-05 17:35:25.021      card  ANON-0000-0000-0025
36    2024-03-05  2024-03-05 17:36:28.571      card  ANON-0000-0000-0026
37    2024-03-05  2024-03-05 17:37:13.659      card  ANON-0000-0000-0027
38    2024-03-05  2024-03-05 17:38:09.354      card  ANON-0000-0000-0009
39    2024-03-05  2024-03-05 17:56:15.776      card  ANON-0000-0000-0028
40    2024-03-05  2024-03-05 18:01:31.242      card  ANON-0000-0000-0028
41    2024-03-06  2024-03-06 12:30:27.089      cash     Cash_Transaction
42    2024-03-06  2024-03-06 13:24:07.667      card  ANON-0000-0000-0012
43    2024-03-06  2024-03-06 13:25:14.351      card  ANON-0000-0000-0012
44    2024-03-06  2024-03-06 14:52:01.761      card  ANON-0000-0000-0029
45    2024-03-06  2024-03-06 14:53:18.344      card  ANON-0000-0000-0029
46    2024-03-07  2024-03-07 10:08:58.945      cash     Cash_Transaction
47    2024-03-07  2024-03-07 10:18:40.543      card  ANON-0000-0000-0030
48    2024-03-07  2024-03-07 11:03:58.976      card  ANON-0000-0000-0031
49    2024-03-07  2024-03-07 11:25:43.977      cash     Cash_Transaction
50    2024-03-07  2024-03-07 15:40:22.606      card  ANON-0000-0000-0032
51    2024-03-07  2024-03-07 15:41:28.784      card  ANON-0000-0000-0033
52    2024-03-08  2024-03-08 10:34:41.283      card  ANON-0000-0000-0012
53    2024-03-08  2024-03-08 12:22:28.653      card  ANON-0000-0000-0034
54    2024-03-08  2024-03-08 13:53:02.042      card  ANON-0000-0000-0035
55    2024-03-08  2024-03-08 14:44:12.686      card  ANON-0000-0000-0012
56    2024-03-08  2024-03-08 14:45:11.048      card  ANON-0000-0000-0033
57    2024-03-08  2024-03-08 14:46:11.155      card  ANON-0000-0000-0012
58    2024-03-08  2024-03-08 18:57:51.451      card  ANON-0000-0000-0036
59    2024-03-08  2024-03-08 18:59:24.941      card  ANON-0000-0000-0037
60    2024-03-09  2024-03-09 11:49:37.292      cash     Cash_Transaction
61    2024-03-09  2024-03-09 12:05:15.559      card  ANON-0000-0000-0038
62    2024-03-09  2024-03-09 12:07:38.275      card  ANON-0000-0000-0039
63    2024-03-09  2024-03-09 12:09:47.714      card  ANON-0000-0000-0012
64    2024-03-09  2024-03-09 12:13:03.521      card  ANON-0000-0000-0040
65    2024-03-09  2024-03-09 12:14:26.458      card  ANON-0000-0000-0040
66    2024-03-09  2024-03-09 13:09:22.229      card  ANON-0000-0000-0041
67    2024-03-09  2024-03-09 13:41:06.167      card  ANON-0000-0000-0042
68    2024-03-09  2024-03-09 13:53:10.408      card  ANON-0000-0000-0043
69    2024-03-09  2024-03-09 13:54:36.828      card  ANON-0000-0000-0043
70    2024-03-09  2024-03-09 14:08:01.829      card  ANON-0000-0000-0009
71    2024-03-09  2024-03-09 14:26:52.873      card  ANON-0000-0000-0044
72    2024-03-09  2024-03-09 19:17:57.572      card  ANON-0000-0000-0009
73    2024-03-09  2024-03-09 19:19:10.084      card  ANON-0000-0000-0009
74    2024-03-10  2024-03-10 07:44:18.538      cash     Cash_Transaction
75    2024-03-10  2024-03-10 07:45:29.441      cash     Cash_Transaction
76    2024-03-10  2024-03-10 10:06:02.960      cash     Cash_Transaction
77    2024-03-10  2024-03-10 11:19:20.764      card  ANON-0000-0000-0045
78    2024-03-10  2024-03-10 17:51:03.048      cash     Cash_Transaction
79    2024-03-10  2024-03-10 19:34:00.478      card  ANON-0000-0000-0046
80    2024-03-10  2024-03-10 19:35:54.712      card  ANON-0000-0000-0046
81    2024-03-11  2024-03-11 10:18:46.724      cash     Cash_Transaction
82    2024-03-11  2024-03-11 11:24:15.022      cash     Cash_Transaction
83    2024-03-11  2024-03-11 11:24:51.565      cash     Cash_Transaction
84    2024-03-11  2024-03-11 11:26:44.221      cash     Cash_Transaction
85    2024-03-11  2024-03-11 11:32:58.781      card  ANON-0000-0000-0035
86    2024-03-11  2024-03-11 16:24:26.401      card  ANON-0000-0000-0047
87    2024-03-11  2024-03-11 16:25:45.664      card  ANON-0000-0000-0047
88    2024-03-11  2024-03-11 16:50:49.608      card  ANON-0000-0000-0048
89    2024-03-12  2024-03-12 10:15:00.297      cash     Cash_Transaction
90    2024-03-12  2024-03-12 10:15:34.543      card  ANON-0000-0000-0033
91    2024-03-12  2024-03-12 10:16:24.886      card  ANON-0000-0000-0033
92    2024-03-12  2024-03-12 11:20:45.632      card  ANON-0000-0000-0049
93    2024-03-12  2024-03-12 12:46:23.275      card  ANON-0000-0000-0004
94    2024-03-12  2024-03-12 12:47:26.027      card  ANON-0000-0000-0004
95    2024-03-12  2024-03-12 16:15:43.325      card  ANON-0000-0000-0050
96    2024-03-13  2024-03-13 11:06:43.038      card  ANON-0000-0000-0048
97    2024-03-13  2024-03-13 11:48:16.753      card  ANON-0000-0000-0004
98    2024-03-13  2024-03-13 12:18:06.336      card  ANON-0000-0000-0051
99    2024-03-13  2024-03-13 12:19:05.128      card  ANON-0000-0000-0051
100   2024-03-13  2024-03-13 12:34:30.315      cash     Cash_Transaction
101   2024-03-13  2024-03-13 14:26:40.875      card  ANON-0000-0000-0052
102   2024-03-13  2024-03-13 15:40:22.261      card  ANON-0000-0000-0053
103   2024-03-13  2024-03-13 15:41:20.424      card  ANON-0000-0000-0053
104   2024-03-13  2024-03-13 16:47:09.373      card  ANON-0000-0000-0054
105   2024-03-14  2024-03-14 10:02:12.241      cash     Cash_Transaction
106   2024-03-14  2024-03-14 10:28:33.017      card  ANON-0000-0000-0055
107   2024-03-14  2024-03-14 10:29:34.283      card  ANON-0000-0000-0055
108   2024-03-14  2024-03-14 13:27:29.536      card  ANON-0000-0000-0012
109   2024-03-14  2024-03-14 13:28:24.527      card  ANON-0000-0000-0012
110   2024-03-14  2024-03-14 13:51:59.905      card  ANON-0000-0000-0056
111   2024-03-14  2024-03-14 13:52:56.248      card  ANON-0000-0000-0057
112   2024-03-14  2024-03-14 15:20:38.367      card  ANON-0000-0000-0058
113   2024-03-14  2024-03-14 16:04:09.506      card  ANON-0000-0000-0059
114   2024-03-14  2024-03-14 16:54:38.202      card  ANON-0000-0000-0050
115   2024-03-14  2024-03-14 18:58:55.854      card  ANON-0000-0000-0019
116   2024-03-14  2024-03-14 19:00:08.663      card  ANON-0000-0000-0012
117   2024-03-15  2024-03-15 10:02:16.533      cash     Cash_Transaction
118   2024-03-15  2024-03-15 10:53:02.180      card  ANON-0000-0000-0060
119   2024-03-15  2024-03-15 18:19:27.922      card  ANON-0000-0000-0012
120   2024-03-16  2024-03-16 12:06:55.209      card  ANON-0000-0000-0061
121   2024-03-16  2024-03-16 12:07:53.915      card  ANON-0000-0000-0061
122   2024-03-16  2024-03-16 15:58:18.458      card  ANON-0000-0000-0009
123   2024-03-16  2024-03-16 16:03:21.738      card  ANON-0000-0000-0009
124   2024-03-16  2024-03-16 16:04:11.444      card  ANON-0000-0000-0012
125   2024-03-16  2024-03-16 17:58:07.241      card  ANON-0000-0000-0062
126   2024-03-17  2024-03-17 10:10:21.399      cash     Cash_Transaction
127   2024-03-17  2024-03-17 12:55:26.065      card  ANON-0000-0000-0063
128   2024-03-18  2024-03-18 11:17:59.671      card  ANON-0000-0000-0064
129   2024-03-18  2024-03-18 15:31:39.725      card  ANON-0000-0000-0003
130   2024-03-18  2024-03-18 15:32:38.239      card  ANON-0000-0000-0003
131   2024-03-18  2024-03-18 15:33:36.708      card  ANON-0000-0000-0003
132   2024-03-19  2024-03-19 10:20:25.996      cash     Cash_Transaction
133   2024-03-19  2024-03-19 14:02:21.536      card  ANON-0000-0000-0065
134   2024-03-19  2024-03-19 14:03:19.765      card  ANON-0000-0000-0065
135   2024-03-19  2024-03-19 15:04:36.309      card  ANON-0000-0000-0049
136   2024-03-19  2024-03-19 16:53:48.706      card  ANON-0000-0000-0066
137   2024-03-19  2024-03-19 19:26:32.677      cash     Cash_Transaction
138   2024-03-20  2024-03-20 11:41:16.403      card  ANON-0000-0000-0012
139   2024-03-20  2024-03-20 12:21:07.728      cash     Cash_Transaction
140   2024-03-20  2024-03-20 12:30:48.968      card  ANON-0000-0000-0049
141   2024-03-20  2024-03-20 13:16:47.394      card  ANON-0000-0000-0067
142   2024-03-20  2024-03-20 16:42:38.117      card  ANON-0000-0000-0050
143   2024-03-20  2024-03-20 17:50:28.781      card  ANON-0000-0000-0068
144   2024-03-21  2024-03-21 10:18:56.977      cash     Cash_Transaction
145   2024-03-21  2024-03-21 12:25:09.194      card  ANON-0000-0000-0012
146   2024-03-21  2024-03-21 12:26:17.428      card  ANON-0000-0000-0012
147   2024-03-21  2024-03-21 17:21:01.453      cash     Cash_Transaction
148   2024-03-21  2024-03-21 17:22:01.353      card  ANON-0000-0000-0012
149   2024-03-21  2024-03-21 19:20:36.508      card  ANON-0000-0000-0069
150   2024-03-22  2024-03-22 10:35:53.619      card  ANON-0000-0000-0070
151   2024-03-22  2024-03-22 13:29:20.343      card  ANON-0000-0000-0071
152   2024-03-22  2024-03-22 16:15:14.448      cash     Cash_Transaction
153   2024-03-22  2024-03-22 17:17:03.724      card  ANON-0000-0000-0012
154   2024-03-22  2024-03-22 17:17:58.991      card  ANON-0000-0000-0012
155   2024-03-22  2024-03-22 17:20:49.490      card  ANON-0000-0000-0050
156   2024-03-23  2024-03-23 10:43:59.559      card  ANON-0000-0000-0072
157   2024-03-23  2024-03-23 10:45:07.157      card  ANON-0000-0000-0073
158   2024-03-23  2024-03-23 13:10:07.661      card  ANON-0000-0000-0074
159   2024-03-23  2024-03-23 13:11:12.230      card  ANON-0000-0000-0074
160   2024-03-23  2024-03-23 14:44:41.276      card  ANON-0000-0000-0075
161   2024-03-23  2024-03-23 15:47:19.062      card  ANON-0000-0000-0076
162   2024-03-23  2024-03-23 15:49:33.813      card  ANON-0000-0000-0076
163   2024-03-23  2024-03-23 16:00:58.386      card  ANON-0000-0000-0009
164   2024-03-24  2024-03-24 10:03:56.005      cash     Cash_Transaction
165   2024-03-24  2024-03-24 18:45:08.397      card  ANON-0000-0000-0077
166   2024-03-25  2024-03-25 10:31:47.250      card  ANON-0000-0000-0009
167   2024-03-25  2024-03-25 11:16:25.671      cash     Cash_Transaction
168   2024-03-25  2024-03-25 14:27:09.163      card  ANON-0000-0000-0078
169   2024-03-25  2024-03-25 14:29:25.343      card  ANON-0000-0000-0017
170   2024-03-25  2024-03-25 18:37:30.650      card  ANON-0000-0000-0024
171   2024-03-25  2024-03-25 19:34:24.542      card  ANON-0000-0000-0079
172   2024-03-26  2024-03-26 10:35:49.679      card  ANON-0000-0000-0055
173   2024-03-26  2024-03-26 10:36:36.151      card  ANON-0000-0000-0055
174   2024-03-26  2024-03-26 10:42:30.170      card  ANON-0000-0000-0080
175   2024-03-26  2024-03-26 11:11:47.335      card  ANON-0000-0000-0009
176   2024-03-26  2024-03-26 13:35:52.773      card  ANON-0000-0000-0003
177   2024-03-26  2024-03-26 13:36:49.644      card  ANON-0000-0000-0032
178   2024-03-26  2024-03-26 13:37:59.723      card  ANON-0000-0000-0059
179   2024-03-26  2024-03-26 13:57:53.677      card  ANON-0000-0000-0050
180   2024-03-26  2024-03-26 15:48:02.270      card  ANON-0000-0000-0081
181   2024-03-26  2024-03-26 18:33:38.568      card  ANON-0000-0000-0024
182   2024-03-26  2024-03-26 18:34:54.648      card  ANON-0000-0000-0009
183   2024-03-27  2024-03-27 11:04:51.174      card  ANON-0000-0000-0003
184   2024-03-27  2024-03-27 11:05:58.236      card  ANON-0000-0000-0003
185   2024-03-27  2024-03-27 12:57:00.462      card  ANON-0000-0000-0082
186   2024-03-27  2024-03-27 13:35:20.039      card  ANON-0000-0000-0083
187   2024-03-27  2024-03-27 14:22:31.662      card  ANON-0000-0000-0012
188   2024-03-27  2024-03-27 14:23:35.380      card  ANON-0000-0000-0012
189   2024-03-27  2024-03-27 18:30:11.833      card  ANON-0000-0000-0084
190   2024-03-27  2024-03-27 19:31:12.442      cash     Cash_Transaction
191   2024-03-28  2024-03-28 14:24:47.092      card  ANON-0000-0000-0085
192   2024-03-28  2024-03-28 17:24:46.244      card  ANON-0000-0000-0012
193   2024-03-28  2024-03-28 17:27:05.304      card  ANON-0000-0000-0012
194   2024-03-28  2024-03-28 17:32:44.652      card  ANON-0000-0000-0086
195   2024-03-29  2024-03-29 10:56:19.495      card  ANON-0000-0000-0087
196   2024-03-29  2024-03-29 12:34:17.383      card  ANON-0000-0000-0088
197   2024-03-29  2024-03-29 12:41:32.125      card  ANON-0000-0000-0088
198   2024-03-29  2024-03-29 13:22:44.618      cash     Cash_Transaction
199   2024-03-30  2024-03-30 11:59:19.854      card  ANON-0000-0000-0069
200   2024-03-30  2024-03-30 13:49:25.815      cash     Cash_Transaction
201   2024-03-30  2024-03-30 16:12:31.786      card  ANON-0000-0000-0017
202   2024-03-30  2024-03-30 16:36:40.513      card  ANON-0000-0000-0009
203   2024-03-30  2024-03-30 16:37:57.553      card  ANON-0000-0000-0009
204   2024-03-31  2024-03-31 10:40:04.523      card  ANON-0000-0000-0089
205   2024-03-31  2024-03-31 19:36:45.000      cash     Cash_Transaction
206   2024-04-01  2024-04-01 10:28:47.601      card  ANON-0000-0000-0004
207   2024-04-01  2024-04-01 10:29:42.318      card  ANON-0000-0000-0004
208   2024-04-01  2024-04-01 10:30:43.735      card  ANON-0000-0000-0004
209   2024-04-01  2024-04-01 11:15:43.836      card  ANON-0000-0000-0009
210   2024-04-01  2024-04-01 17:01:42.924      cash     Cash_Transaction
211   2024-04-01  2024-04-01 18:18:42.372      card  ANON-0000-0000-0024
212   2024-04-01  2024-04-01 18:45:27.436      card  ANON-0000-0000-0090
213   2024-04-02  2024-04-02 10:01:14.022      card  ANON-0000-0000-0001
214   2024-04-02  2024-04-02 16:18:34.169      card  ANON-0000-0000-0003
215   2024-04-02  2024-04-02 16:19:28.460      card  ANON-0000-0000-0003
216   2024-04-02  2024-04-02 19:59:31.942      cash     Cash_Transaction
217   2024-04-03  2024-04-03 10:19:13.644      card  ANON-0000-0000-0003
218   2024-04-03  2024-04-03 10:20:07.655      card  ANON-0000-0000-0003
219   2024-04-03  2024-04-03 13:12:05.367      card  ANON-0000-0000-0012
220   2024-04-03  2024-04-03 15:36:11.735      cash     Cash_Transaction
221   2024-04-04  2024-04-04 10:44:55.988      card  ANON-0000-0000-0091
222   2024-04-04  2024-04-04 11:26:38.085      card  ANON-0000-0000-0092
223   2024-04-04  2024-04-04 11:27:48.411      card  ANON-0000-0000-0093
224   2024-04-04  2024-04-04 12:23:02.216      card  ANON-0000-0000-0094
225   2024-04-04  2024-04-04 19:42:07.740      cash     Cash_Transaction
226   2024-04-05  2024-04-05 10:40:42.728      card  ANON-0000-0000-0095
227   2024-04-05  2024-04-05 10:42:06.204      card  ANON-0000-0000-0012
228   2024-04-05  2024-04-05 11:06:14.643      card  ANON-0000-0000-0096
229   2024-04-05  2024-04-05 12:14:27.975      card  ANON-0000-0000-0097
230   2024-04-05  2024-04-05 14:23:40.387      card  ANON-0000-0000-0098
231   2024-04-05  2024-04-05 14:24:50.417      card  ANON-0000-0000-0098
232   2024-04-05  2024-04-05 15:30:50.383      cash     Cash_Transaction
233   2024-04-05  2024-04-05 15:54:15.768      cash     Cash_Transaction
234   2024-04-05  2024-04-05 15:55:30.947      cash     Cash_Transaction
235   2024-04-05  2024-04-05 16:17:43.975      cash     Cash_Transaction
236   2024-04-05  2024-04-05 16:18:23.558      card  ANON-0000-0000-0003
237   2024-04-06  2024-04-06 12:32:31.398      card  ANON-0000-0000-0099
238   2024-04-06  2024-04-06 14:13:18.733      card  ANON-0000-0000-0040
239   2024-04-06  2024-04-06 14:14:27.029      card  ANON-0000-0000-0040
240   2024-04-06  2024-04-06 14:49:50.183      card  ANON-0000-0000-0009
241   2024-04-07  2024-04-07 10:12:53.204      card  ANON-0000-0000-0091
242   2024-04-07  2024-04-07 12:44:31.936      card  ANON-0000-0000-0040
243   2024-04-07  2024-04-07 12:46:05.118      card  ANON-0000-0000-0040
244   2024-04-07  2024-04-07 14:16:24.949      card  ANON-0000-0000-0100
245   2024-04-07  2024-04-07 14:17:30.628      card  ANON-0000-0000-0100
246   2024-04-07  2024-04-07 18:01:16.608      card  ANON-0000-0000-0101
247   2024-04-07  2024-04-07 18:02:03.878      card  ANON-0000-0000-0101
248   2024-04-08  2024-04-08 10:58:21.106      card  ANON-0000-0000-0102
249   2024-04-08  2024-04-08 10:59:27.558      card  ANON-0000-0000-0103
250   2024-04-08  2024-04-08 11:01:20.464      card  ANON-0000-0000-0012
251   2024-04-08  2024-04-08 11:04:47.030      card  ANON-0000-0000-0104
252   2024-04-08  2024-04-08 12:54:25.897      cash     Cash_Transaction
253   2024-04-08  2024-04-08 15:43:36.881      cash     Cash_Transaction
254   2024-04-08  2024-04-08 16:41:37.806      card  ANON-0000-0000-0017
255   2024-04-08  2024-04-08 18:18:09.713      card  ANON-0000-0000-0105
256   2024-04-08  2024-04-08 19:22:27.477      card  ANON-0000-0000-0024
257   2024-04-08  2024-04-08 19:23:59.268      card  ANON-0000-0000-0106
258   2024-04-09  2024-04-09 10:22:27.359      cash     Cash_Transaction
259   2024-04-09  2024-04-09 10:24:10.103      cash     Cash_Transaction
260   2024-04-09  2024-04-09 11:42:28.468      card  ANON-0000-0000-0091
261   2024-04-09  2024-04-09 15:11:48.720      card  ANON-0000-0000-0107
262   2024-04-09  2024-04-09 17:25:23.936      card  ANON-0000-0000-0049
263   2024-04-10  2024-04-10 10:21:26.175      cash     Cash_Transaction
264   2024-04-10  2024-04-10 17:55:07.018      cash     Cash_Transaction
265   2024-04-10  2024-04-10 17:55:31.244      card  ANON-0000-0000-0108
266   2024-04-10  2024-04-10 18:24:59.290      card  ANON-0000-0000-0009
267   2024-04-10  2024-04-10 20:04:05.386      card  ANON-0000-0000-0109
268   2024-04-11  2024-04-11 10:41:23.155      card  ANON-0000-0000-0110
269   2024-04-11  2024-04-11 10:42:59.365      card  ANON-0000-0000-0110
270   2024-04-11  2024-04-11 16:35:23.069      card  ANON-0000-0000-0017
271   2024-04-11  2024-04-11 19:16:56.588      card  ANON-0000-0000-0106

In [30]:
data.isna().sum()

date           0
datetime       0
cash_type      0
card           0
money          0
coffee_name    0
dtype: int64

In [31]:
# see the duplicates values and removal

In [34]:
data.duplicated().sum()

np.int64(0)

In [35]:
# if you see the dupliacates

In [36]:
#data=data.drop_duplicates()

In [37]:
# how to see the duplicates on particular column

In [40]:
#data['cash_type'].duplicated()

In [39]:
# true means values duplicated 
# false means not duplicated

In [41]:
#data['cash_type'].duplicated().sum()

np.int64(3634)

In [42]:
data['card'].duplicated().sum()

np.int64(2319)

# Outliers

In [43]:
# outliers is a part of data cleaning they are the extreme values in the data 

# students - weight :60,65,70,45,67,100
# 100 value is the outlier of us
#it means one out 
# outliers are not good for our data becuase it changes the avergae leading not a normal distrbution of data and hence increasing the model inaccracy 
# outliers removal - IOR(inter quartile range , zscore)

# Data analysis

In [44]:
#total sales

In [45]:
data['money'].sum()

np.float64(115431.58)

In [46]:
#average transaction values

In [47]:
data['money'].mean()

np.float64(31.74685918591859)

In [48]:
#maximum

In [49]:
data['money'].max()

40.0

In [50]:
#minimum

In [51]:
data['money'].min()

18.12

In [52]:
# python - aggrgeate functions - sum , avg, min , max- numpy , numercial data

In [53]:
#group by
# grouping the data to find the insights

In [58]:
# sales by coffee type
# this one we wrote the group by with orders by and we also checked count , sum and mean 
# we dont have order by we have sort_values ascending =False then data is sort based on descending order

In [55]:
data.groupby('coffee_name')['money'].agg(['count','sum','mean']).sort_values('sum',ascending=False)

                     count       sum       mean
coffee_name
Latte                  782  27866.30  35.634655
Americano with Milk    824  25269.12  30.666408
Cappuccino             501  18034.14  35.996287
Americano              578  15062.26  26.059273
Hot Chocolate          282  10172.46  36.072553
Cocoa                  243   8678.16  35.712593
Cortado                292   7534.86  25.804315
Espresso               134   2814.28  21.002090

In [56]:
#if we want the coffe sales by its type

In [57]:
data.groupby('coffee_name')['money'].sum()

coffee_name
Americano              15062.26
Americano with Milk    25269.12
Cappuccino             18034.14
Cocoa                   8678.16
Cortado                 7534.86
Espresso                2814.28
Hot Chocolate          10172.46
Latte                  27866.30
Name: money, dtype: float64

In [62]:
# order by and groupb y
# you have to only use ascending

In [61]:
data.groupby('coffee_name')['money'].sum().sort_values(ascending=True)

coffee_name
Espresso                2814.28
Cortado                 7534.86
Cocoa                   8678.16
Hot Chocolate          10172.46
Americano              15062.26
Cappuccino             18034.14
Americano with Milk    25269.12
Latte                  27866.30
Name: money, dtype: float64

In [63]:
# sales over time

In [68]:
data.groupby('date')['money'].sum().sort_values(ascending=False)

date
2024-10-11    836.66
2025-02-03    796.00
2025-02-05    760.24
2025-03-03    737.72
2024-10-17    726.46
2025-02-24    723.02
2025-03-14    704.88
2025-02-21    695.08
2024-09-22    679.88
2025-02-10    662.76
2024-09-17    661.76
2024-10-06    656.40
2024-07-30    650.48
2025-02-19    646.60
2025-03-21    636.80
2024-07-31    633.84
2025-03-19    623.56
2024-10-21    615.74
2025-02-27    610.84
2024-10-28    599.58
2025-03-20    597.60
2025-02-17    592.70
2025-03-05    591.24
2024-10-29    589.78
2024-11-05    588.32
2024-10-08    584.88
2025-02-20    581.44
2024-10-15    579.98
2024-09-07    579.94
2024-05-23    575.40
2025-02-12    570.18
2025-02-26    570.18
2024-05-20    559.02
2025-02-18    555.48
2025-03-10    554.02
2025-03-07    554.02
2025-03-18    549.12
2024-10-20    547.66
2025-03-12    544.22
2024-11-09    539.32
2024-10-14    528.06
2024-05-26    526.60
2024-10-30    523.16
2024-10-18    521.70
2024-09-09    518.74
2024-09-03    513.84
2024-10-26    513.36
2024-12-31    508.46
2025-02-07    508.46
2025-02-28    505.02
2024-05-31    499.96
2024-10-24    497.20
2024-04-20    494.30
2024-10-10    487.40
2025-01-11    487.40
2024-10-01    482.50
2024-09-27    481.02
2024-03-09    479.40
2024-12-21    477.60
2024-06-04    474.18
2025-03-04    474.16
2024-10-25    472.70
2024-11-14    471.24
2024-12-01    466.34
2024-07-26    461.42
2025-02-14    458.00
2024-09-24    448.20
2024-08-15    446.72
2024-08-11    443.30
2024-10-16    441.84
2024-06-09    436.46
2024-04-14    434.30
2025-02-11    432.04
2024-09-21    428.60
2024-09-30    427.14
2024-12-03    425.68
2025-03-11    420.78
2024-11-16    420.78
2024-05-19    417.84
2024-10-23    415.88
2024-06-16    408.54
2024-11-03    406.08
2024-09-05    405.58
2024-06-21    403.64
2024-05-14    403.64
2025-03-17    401.18
2024-10-07    399.72
2024-03-14    397.10
2024-05-29    396.60
2024-03-01    396.30
2025-02-13    396.28
2024-11-08    394.82
2025-02-06    394.82
2024-12-25    394.82
2024-08-05    392.36
2025-01-31    389.92
2024-06-01    386.80
2024-06-06    385.52
2024-08-13    382.56
2024-06-19    380.62
2024-06-13    379.14
2024-08-12    377.66
2024-03-26    376.70
2024-10-02    373.76
2024-11-25    373.76
2024-07-27    372.76
2024-05-28    372.10
2024-05-22    370.82
2024-05-30    370.82
2025-03-06    370.32
2024-09-29    368.86
2024-11-19    368.86
2024-05-27    365.92
2025-03-13    365.42
2024-10-09    365.42
2025-03-22    365.42
2024-09-28    362.98
2024-04-05    362.10
2025-02-04    360.52
2024-11-15    359.06
2024-08-03    358.06
2024-08-20    358.06
2025-02-25    355.62
2024-08-23    353.16
2024-04-18    352.70
2024-05-15    350.82
2025-02-01    349.26
2024-03-03    349.10
2024-08-14    348.26
2024-07-07    346.32
2024-05-07    344.08
2025-01-15    342.90
2024-11-11    342.90
2024-04-08    340.20
2024-07-23    339.94
2024-12-08    339.46
2024-03-05    338.50
2024-09-16    336.52
2024-08-01    335.04
2024-12-14    334.56
2024-11-26    333.10
2024-12-19    333.10
2024-07-24    330.14
2025-01-16    328.20
2024-05-16    327.34
2024-06-17    323.30
2024-11-12    321.84
2024-07-29    321.82
2024-08-10    321.82
2024-12-04    318.40
2024-10-19    316.94
2024-05-21    314.90
2024-05-06    314.58
2025-02-16    313.50
2025-01-27    313.50
2025-01-20    313.50
2025-01-04    313.50
2024-12-23    313.50
2025-01-17    312.04
2024-07-18    312.02
2024-08-17    312.02
2024-09-12    310.54
2024-07-03    310.08
2024-06-05    310.08
2024-05-17    306.36
2024-07-05    303.70
2024-04-13    302.40
2024-04-26    300.28
2024-09-04    298.80
2024-11-17    297.34
2025-02-09    297.34
2024-08-26    297.32
2024-05-09    295.38
2024-09-01    293.90
2024-05-11    293.24
2025-02-15    292.44
2024-09-10    289.00
2024-12-30    287.54
2024-11-02    287.54
2024-06-29    287.06
2024-03-23    285.10
2024-05-18    283.44
2024-12-05    282.64
2025-01-02    282.64
2024-08-07    279.20
2024-08-18    279.20
2024-09-25    279.20
2024-09-23    279.20
2025-01-28    277.74
2024-04-16    276.50
2024-12-16    276.28
2024-03-11    275.20
2024-09-06    274.30
2024-10-13    272.84
2024-10-22    272.84
2025-01-30    272.84
2025-01-09    272.84
2024-12-02    272.84
2024-04-30    272.36
2024-04-24    272.36
2024-05-12    272.36
2024-03-27    271.70
2024-10-03    271.38
2024-07-25    269.40
2024-10-04    267.94
2024-12-20    267.94
2024-12-13    266.48
2024-03-08    265.50
2024-06-15    262.56
2024-11-06    261.58
2024-11-21    261.58
2024-12-28    261.58
2025-01-14    261.58
2024-04-19    261.10
2024-09-26    261.08
2024-04-29    257.66
2024-03-13    256.20
2024-05-25    254.92
2025-01-13    251.78
2025-01-21    251.78
2024-06-03    251.70
2024-08-06    247.86
2024-11-23    246.88
2024-05-02    245.72
2025-02-02    245.42
2024-09-11    242.96
2024-07-19    242.96
2024-04-01    242.80
2025-03-01    241.98
2025-03-09    241.98
2024-04-07    241.50
2024-12-22    240.52
2024-12-27    237.08
2024-11-29    235.62
2024-06-18    234.64
2024-09-02    233.16
2025-03-08    232.18
2024-03-10    231.60
2024-11-04    230.72
2024-11-07    230.72
2025-01-24    230.72
2024-03-02    228.10
2024-03-12    228.10
2024-06-10    226.32
2025-03-15    225.82
2024-12-11    225.82
2024-11-01    225.82
2024-12-17    225.82
2024-03-25    223.60
2024-06-24    221.42
2024-06-20    221.42
2024-06-12    221.42
2024-12-24    220.92
2025-01-22    220.92
2024-03-07    220.10
2024-03-19    219.90
2024-08-09    218.46
2024-12-29    217.48
2024-10-12    216.02
2024-11-22    214.56
2024-03-20    213.90
2024-06-02    212.80
2025-02-08    212.58
2024-06-11    211.62
2025-01-03    211.12
2024-05-24    210.14
2024-08-08    208.66
2024-03-21    205.20
2025-03-23    204.76
2024-11-28    204.76
2024-11-18    204.76
2024-11-10    204.76
2024-08-22    200.34
2024-07-20    200.34
2024-04-17    199.20
2024-06-26    196.92
2024-12-12    196.42
2024-09-20    195.44
2024-11-13    194.96
2024-11-30    194.96
2024-07-02    192.02
2024-08-21    190.54
2025-02-23    190.06
2024-03-30    189.90
2024-03-22    189.40
2024-09-13    187.12
2024-08-04    187.12
2024-04-09    186.10
2025-03-02    185.16
2024-12-07    185.16
2024-04-04    185.00
2024-03-16    183.20
2024-06-23    178.80
2024-04-22    176.46
2024-10-05    175.36
2024-04-23    173.90
2024-07-14    172.42
2024-03-06    170.20
2024-10-27    169.00
2024-04-11    169.00
2024-04-28    169.00
2024-10-31    169.00
2024-06-22    169.00
2024-08-25    167.52
2024-04-10    166.40
2025-03-16    164.10
2024-07-06    164.10
2025-01-10    164.10
2024-06-28    159.20
2024-09-19    157.72
2024-03-29    156.10
2025-01-12    154.30
2024-12-09    154.30
2024-07-12    154.30
2024-04-15    150.40
2024-06-07    149.40
2024-05-10    148.44
2024-09-15    147.92
2024-07-09    144.50
2024-12-06    143.04
2024-08-31    143.02
2024-06-25    141.08
2024-04-06    140.10
2024-08-02    139.60
2024-07-08    139.60
2025-02-22    139.60
2024-11-20    138.14
2024-12-18    138.14
2025-01-18    138.14
2024-09-08    138.12
2024-04-02    136.50
2024-06-08    136.18
2024-03-04    135.20
2024-06-27    131.28
2024-06-30    131.28
2025-01-08    128.34
2024-08-24    128.32
2024-04-03    126.50
2024-06-14    126.38
2024-03-28    125.40
2024-09-18    121.48
2024-08-19    121.48
2024-04-25    121.48
2024-07-21    121.48
2024-08-16    120.00
2024-07-11    116.58
2024-03-18    115.60
2024-05-03    114.44
2024-08-28    111.68
2024-03-15    107.60
2025-01-07    107.28
2024-12-15    107.28
2024-07-22    106.78
2024-04-21    104.64
2025-01-29    103.84
2024-07-01     98.46
2025-01-05     97.48
2025-01-25     97.48
2024-05-13     90.82
2024-08-30     88.66
2024-07-10     83.76
2024-07-28     78.86
2024-03-24     78.70
2024-03-17     68.90
2024-03-31     68.70
2024-04-12     67.60
2024-07-13     65.64
2024-09-14     65.64
2024-12-10     61.72
2024-07-16     60.74
2024-07-04     60.74
2024-12-26     56.82
2025-01-26     47.02
2024-05-08     37.72
2024-04-27     37.72
2024-11-24     35.76
2024-07-15     32.82
2024-08-27     32.82
2024-07-17     27.92
2025-01-06     25.96
2024-08-29     23.02
Name: money, dtype: float64